#! /bin/sh
ww=2475
hh=3300

(
cd PPPL-TM-364-R
x=89
y=68
w=2426
h=3200
ox=`expr "(" $ww - $w ")" / 2`
oy=`expr "(" $hh - $h ")" / 2`
for i in x-*c.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done

x=582
y=477
w=1650
h=2481
ox=`expr "(" $ww - $w ")" / 2 + 30`
oy=`expr "(" $hh - $h ")" / 2 + 50`
for i in x-*e.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done

x=370
y=471
w=1650
h=2481
ox=`expr "(" $ww - $w ")" / 2 + 30`
oy=`expr "(" $hh - $h ")" / 2 + 50`
for i in x-*o.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done
)

(
cd PPPL-TM-387
x=72
y=90
w=2375
h=3145
ox=`expr "(" $ww - $w ")" / 2 + 20`
oy=`expr "(" $hh - $h ")" / 2`
for i in x-*c.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done

x=305
y=288
w=1795
h=2895
ox=`expr "(" $ww - $w ")" / 2 + 0`
oy=`expr "(" $hh - $h ")" / 2 + 50`
for i in x-*e.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done

x=315
y=291
w=1795
h=2895
ox=`expr "(" $ww - $w ")" / 2 + 0`
oy=`expr "(" $hh - $h ")" / 2 + 50`
for i in x-*o.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done
)

(
cd PPPL-TM-393
x=101
y=137
w=2375
h=3093
ox=`expr "(" $ww - $w ")" / 2`
oy=`expr "(" $hh - $h ")" / 2`
for i in x-*c.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done

x=296
y=181
w=2116
h=2922
ox=`expr "(" $ww - $w ")" / 2 + 0`
oy=`expr "(" $hh - $h ")" / 2 + 0`
for i in x-*e.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done

x=131
y=185
w=2116
h=2922
ox=`expr "(" $ww - $w ")" / 2 + 0`
oy=`expr "(" $hh - $h ")" / 2 + 0`
for i in x-*o.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done
)

(
cd PPPL-TM-397-R
x=107
y=61
w=2357
h=3038
ox=`expr "(" $ww - $w ")" / 2 + 30`
oy=`expr "(" $hh - $h ")" / 2`
for i in x-*c.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done

x=401
y=179
w=1770
h=2883
ox=`expr "(" $ww - $w ")" / 2 + 0`
oy=`expr "(" $hh - $h ")" / 2 + 0`
for i in x-*e.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done

x=417
y=208
w=1770
h=2883
ox=`expr "(" $ww - $w ")" / 2 + 0`
oy=`expr "(" $hh - $h ")" / 2 + 0`
for i in x-*o.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done
)

(
cd PPPL-TM-404
x=78
y=117
w=2370
h=3123
ox=`expr "(" $ww - $w ")" / 2 + 30`
oy=`expr "(" $hh - $h ")" / 2`
for i in x-*c.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done

x=473
y=364
w=1914
h=2772
ox=`expr "(" $ww - $w ")" / 2 + 0`
oy=`expr "(" $hh - $h ")" / 2 - 50`
for i in x-*e.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done

x=262
y=357
w=1914
h=2772
ox=`expr "(" $ww - $w ")" / 2 + 0`
oy=`expr "(" $hh - $h ")" / 2 - 50`
for i in x-*o.pbm; do
  pnmcut $x $y $w $h $i | pnmpastea ../blank.pbm $ox $oy > $i.a
done
)
